name: Build and publish to docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (ignore peer conflicts)
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Publish to docs (copy + stamp)
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r dist/* docs/
          # Add a stamp so there's always a change to commit
          date -u +"%Y-%m-%dT%H:%M:%SZ" > docs/buildstamp.txt
          echo "Docs now contain:"
          ls -la docs

      - name: Commit & push changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: build site to docs [skip ci]"
          file_pattern: docs/**
